# Generated by Django 3.2.15 on 2022-09-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='name',
            field=models.CharField(default="frank's bookstore", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='bookstores', to='books.Book'),
        ),
    ]
